[package]
name = "mrml"
description = "Rust implementation of MJML renderer"
keywords = ["email", "mjml"]
version = "1.2.11"
authors = ["Jérémie Drouet <jeremie.drouet@gmail.com>"]
edition = "2018"
license-file = "license.md"
repository = "https://github.com/jolimail/mrml-core/"
readme = "readme.md"

include = ["src/*", "Cargo.toml"]

[badges]
codecov = { repository = "jdrouet/mrml", branch = "main" }
travis-ci = { repository = "jdrouet/mrml", branch = "main" }

[features]
default = ["json", "parse", "print", "render"]
json = ["serde", "serde_json"]
parse = ["mrml-parse-macros", "xmlparser"]
print = ["mrml-print-macros"]
render = ["rand"]
orderedmap = ["indexmap", "rustc-hash"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { default-features = false, features = [
  "std",
  "std_rng",
], version = "0.8", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true }
xmlparser = { version = "0.13", optional = true }
indexmap = { version = "1.9", features = ["serde-1"], optional = true }
rustc-hash = { version = "1.1", optional = true }

# macros
mrml-macros = { path = "./lib/mrml-macros" }
mrml-parse-macros = { path = "./lib/mrml-parse-macros", optional = true }
mrml-print-macros = { path = "./lib/mrml-print-macros", optional = true }

[dev-dependencies]
criterion = "0.4"

[workspace]
members = [
  "./lib/common-macros",
  "./lib/mrml-macros",
  "./lib/mrml-parse-macros",
  "./lib/mrml-print-macros",
]

[[bench]]
name = "basic"
path = "benches/basic.rs"
harness = false

[[bench]]
name = "template"
path = "benches/template.rs"
harness = false
